'use client'
import { useState } from 'react'

const budgets = ['Budget ($50/day)', 'Mid-range ($100-200/day)', 'Luxury ($500+/day)']
const styles = ['Adventure', 'Cultural', 'Relaxation', 'Food & Gastronomy', 'Family', 'Romantic', 'Business']
const durations = [3, 5, 7, 10, 14]

export default function TripPlanner() {
  const [destination, setDestination] = useState('')
  const [days, setDays] = useState(7)
  const [budget, setBudget] = useState('Mid-range ($100-200/day)')
  const [style, setStyle] = useState('Cultural')
  const [data, setData] = useState<any>(null)
  const [loading, setLoading] = useState(false)
  const [activeDay, setActiveDay] = useState(0)

  const generate = async () => {
    if (!destination) return
    setLoading(true)
    setData(null)
    try {
      const res = await fetch('/api/tripplanner', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ destination, days, budget, style })
      })
      const json = await res.json()
      setData(json)
      setActiveDay(0)
    } catch {}
    setLoading(false)
  }

  const exportPDF = () => {
    if (!data) return
    const w = window.open('', '_blank')
    if (!w) return
    w.document.write(`<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${data.title}</title>
    <style>body{font-family:'Helvetica Neue',sans-serif;max-width:800px;margin:0 auto;padding:40px;color:#1a1a1a}
    .cover{background:linear-gradient(135deg,#667eea,#764ba2);color:white;padding:60px;border-radius:20px;text-align:center;margin-bottom:40px}
    .day{border:1px solid #e5e7eb;border-radius:12px;padding:24px;margin-bottom:24px;page-break-inside:avoid}
    .day-title{font-size:1.3rem;font-weight:bold;color:#6366f1;margin-bottom:16px}
    .period{background:#f3f4f6;border-radius:8px;padding:12px;margin-bottom:10px}
    .period-title{font-weight:bold;color:#374151;margin-bottom:4px}
    .tips-box{background:#fef3c7;border-left:4px solid #f59e0b;padding:10px;border-radius:0 8px 8px 0;margin-top:8px;font-size:0.9rem}
    .footer{text-align:center;margin-top:40px;color:#9ca3af;font-size:0.85rem}</style>
    </head><body>
    <div class="cover"><div style="font-size:4rem">✈️</div><h1>${data.title}</h1><p>${data.description}</p><p style="margin-top:16px;opacity:0.8">Budget: ${data.budget_total} • ${days} Days</p></div>
    ${data.days?.map((d: any) => `<div class="day"><div class="day-title">📅 ${d.date} — ${d.theme}</div>
    <div class="period"><div class="period-title">🌅 Morning</div><strong>${d.morning?.activity}</strong> at ${d.morning?.location}<br>Duration: ${d.morning?.duration} • Cost: ${d.morning?.cost}<div class="tips-box">💡 ${d.morning?.tips}</div></div>
    <div class="period"><div class="period-title">☀️ Afternoon</div><strong>${d.afternoon?.activity}</strong> at ${d.afternoon?.location}<br>Duration: ${d.afternoon?.duration} • Cost: ${d.afternoon?.cost}</div>
    <div class="period"><div class="period-title">🌙 Evening</div><strong>${d.evening?.activity}</strong> at ${d.evening?.location}<br>Cost: ${d.evening?.cost}</div>
    <p style="margin-top:12px">🏨 <strong>Stay:</strong> ${d.accommodation}</p>
    <p>🍽️ <strong>Meals:</strong> ${d.meals?.join(' • ')}</p></div>`).join('')}
    <div class="footer">Generated by ⚡ Nexoro AI Travel Planner</div></body></html>`)
    w.document.close()
    w.print()
  }

  return (
    <main className="min-h-screen bg-gray-950 text-white p-4 md:p-8">
      <div className="max-w-5xl mx-auto space-y-6">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <h1 className="text-3xl font-bold">✈️ Trip Planner IA</h1>
            <p className="text-gray-500 mt-1">Guide touristique complet généré par IA</p>
          </div>
          {data && <button onClick={exportPDF} className="bg-green-600 hover:bg-green-500 text-white font-semibold py-2 px-6 rounded-xl">📥 Export PDF</button>}
        </div>

        <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 space-y-4">
          <input value={destination} onChange={e => setDestination(e.target.value)}
            placeholder="🌍 Destination — Ex: Paris, Tokyo, New York, Dubai, Marrakech..."
            className="w-full bg-gray-800 border border-gray-700 rounded-xl p-4 text-white placeholder-gray-500 focus:outline-none focus:border-indigo-500 text-lg" />
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label className="text-xs text-gray-400 mb-2 block">Duration</label>
              <div className="flex gap-2 flex-wrap">
                {durations.map(d => (
                  <button key={d} onClick={() => setDays(d)}
                    className={`px-3 py-2 rounded-xl text-sm font-bold transition-all ${days === d ? 'bg-indigo-600 text-white' : 'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}>
                    {d}d
                  </button>
                ))}
              </div>
            </div>
            <div>
              <label className="text-xs text-gray-400 mb-2 block">Style</label>
              <select value={style} onChange={e => setStyle(e.target.value)}
                className="w-full bg-gray-800 border border-gray-700 rounded-xl p-2 text-white focus:outline-none focus:border-indigo-500">
                {styles.map(s => <option key={s}>{s}</option>)}
              </select>
            </div>
            <div>
              <label className="text-xs text-gray-400 mb-2 block">Budget</label>
              <select value={budget} onChange={e => setBudget(e.target.value)}
                className="w-full bg-gray-800 border border-gray-700 rounded-xl p-2 text-white focus:outline-none focus:border-indigo-500">
                {budgets.map(b => <option key={b}>{b}</option>)}
              </select>
            </div>
          </div>

          <button onClick={generate} disabled={loading || !destination}
            className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 disabled:opacity-50 text-white font-bold py-4 rounded-xl transition-all text-lg">
            {loading ? '✈️ Planning your trip...' : `✈️ Plan ${days} days in ${destination || '...'}`}
          </button>
        </div>

        {data && (
          <div className="space-y-4">
            <div className="bg-gradient-to-r from-blue-600 to-indigo-600 rounded-2xl p-6 text-center">
              <div className="text-5xl mb-3">✈️</div>
              <h2 className="text-2xl font-bold">{data.title}</h2>
              <p className="text-white/80 mt-2">{data.description}</p>
              <div className="flex gap-4 justify-center mt-4 flex-wrap">
                <span className="bg-white/20 px-4 py-2 rounded-full text-sm">💰 {data.budget_total}</span>
                <span className="bg-white/20 px-4 py-2 rounded-full text-sm">📅 {days} Days</span>
                <span className="bg-white/20 px-4 py-2 rounded-full text-sm">🌍 {destination}</span>
              </div>
            </div>

            {/* Day tabs */}
            <div className="flex gap-2 overflow-x-auto pb-2">
              {data.days?.map((_: any, i: number) => (
                <button key={i} onClick={() => setActiveDay(i)}
                  className={`px-4 py-2 rounded-xl text-sm font-semibold whitespace-nowrap transition-all ${activeDay === i ? 'bg-indigo-600 text-white' : 'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}>
                  Day {i + 1}
                </button>
              ))}
            </div>

            {data.days?.[activeDay] && (
              <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 space-y-4">
                <h3 className="text-xl font-bold text-indigo-400">{data.days[activeDay].date} — {data.days[activeDay].theme}</h3>
                {['morning', 'afternoon', 'evening'].map(period => {
                  const p = data.days[activeDay][period]
                  const icons: Record<string, string> = { morning: '🌅', afternoon: '☀️', evening: '🌙' }
                  return p ? (
                    <div key={period} className="bg-gray-800 rounded-xl p-4">
                      <div className="flex items-center gap-2 mb-2">
                        <span className="text-xl">{icons[period]}</span>
                        <span className="font-semibold capitalize">{period}</span>
                      </div>
                      <p className="font-bold text-white">{p.activity}</p>
                      <p className="text-gray-400 text-sm">📍 {p.location} • ⏱️ {p.duration} • 💰 {p.cost}</p>
                      {p.tips && <p className="text-yellow-400 text-xs mt-2 bg-yellow-900/20 p-2 rounded-lg">💡 {p.tips}</p>}
                    </div>
                  ) : null
                })}
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-gray-800 rounded-xl p-3">
                    <p className="text-xs text-gray-400 mb-1">🏨 Accommodation</p>
                    <p className="text-sm font-semibold">{data.days[activeDay].accommodation}</p>
                  </div>
                  <div className="bg-gray-800 rounded-xl p-3">
                    <p className="text-xs text-gray-400 mb-1">🍽️ Meals</p>
                    <p className="text-sm">{data.days[activeDay].meals?.join(' • ')}</p>
                  </div>
                </div>
              </div>
            )}

            {data.tips && (
              <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6">
                <h3 className="font-semibold mb-3">💡 Travel Tips</h3>
                <ul className="space-y-2">
                  {data.tips.map((tip: string, i: number) => (
                    <li key={i} className="text-gray-400 text-sm flex gap-2"><span className="text-green-400">✓</span>{tip}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}
      </div>
    </main>
  )
}
