'use client'
import { useState } from 'react'

const styles = ['Modern & Minimal', 'Luxury & Premium', 'Colorful & Fun', 'Professional B2B', 'Eco & Natural']
const languages = ['English', 'French', 'Arabic', 'Spanish']

export default function Catalogue() {
  const [business, setBusiness] = useState('')
  const [products, setProducts] = useState('')
  const [style, setStyle] = useState('Modern & Minimal')
  const [language, setLanguage] = useState('English')
  const [data, setData] = useState<any>(null)
  const [loading, setLoading] = useState(false)

  const generate = async () => {
    if (!business || !products) return
    setLoading(true)
    setData(null)
    try {
      const res = await fetch('/api/catalogue', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ business, products, style, language })
      })
      const json = await res.json()
      setData(json)
    } catch {}
    setLoading(false)
  }

  const exportPDF = () => {
    if (!data) return
    const w = window.open('', '_blank')
    if (!w) return
    w.document.write(`<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${data.business_name}</title>
    <style>
      *{margin:0;padding:0;box-sizing:border-box}
      body{font-family:'Helvetica Neue',sans-serif;color:#1a1a1a}
      .cover{background:linear-gradient(135deg,#1a1a2e,#6366f1);color:white;padding:80px 60px;text-align:center}
      .cover h1{font-size:3rem;font-weight:900;margin-bottom:10px}
      .cover p{font-size:1.2rem;opacity:0.9;margin-bottom:8px}
      .content{padding:40px}
      .category{margin-bottom:40px}
      .cat-title{font-size:1.5rem;font-weight:800;color:#6366f1;margin-bottom:20px;padding-bottom:8px;border-bottom:3px solid #6366f1}
      .products-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:20px}
      .product{border:1px solid #e5e7eb;border-radius:12px;padding:20px;position:relative}
      .badge{position:absolute;top:12px;right:12px;background:#6366f1;color:white;padding:4px 10px;border-radius:20px;font-size:0.75rem;font-weight:700}
      .product-emoji{font-size:2.5rem;margin-bottom:10px}
      .product-name{font-size:1.1rem;font-weight:700;margin-bottom:6px}
      .product-desc{font-size:0.85rem;color:#6b7280;margin-bottom:10px;line-height:1.5}
      .product-price{font-size:1.3rem;font-weight:900;color:#6366f1}
      .features{margin-top:8px}
      .feature{font-size:0.8rem;color:#374151;padding:2px 0}
      .feature::before{content:"✓ ";color:#10b981;font-weight:bold}
      .footer{background:#1a1a2e;color:white;padding:20px;text-align:center;font-size:0.8rem;opacity:0.7}
      @media print{.product{page-break-inside:avoid}}
    </style></head><body>
    <div class="cover">
      <h1>${data.business_name}</h1>
      <p>${data.tagline}</p>
      <p style="opacity:0.7;font-size:0.9rem">${data.description}</p>
    </div>
    <div class="content">
      ${data.categories?.map((cat: any) => `
      <div class="category">
        <div class="cat-title">${cat.emoji} ${cat.name}</div>
        <div class="products-grid">
          ${cat.products?.map((p: any) => `
          <div class="product">
            ${p.badge ? `<div class="badge">${p.badge}</div>` : ''}
            <div class="product-emoji">${p.emoji}</div>
            <div class="product-name">${p.name}</div>
            <div class="product-desc">${p.description}</div>
            <div class="product-price">${p.price}</div>
            <div class="features">${p.features?.map((f: string) => `<div class="feature">${f}</div>`).join('') || ''}</div>
          </div>`).join('')}
        </div>
      </div>`).join('')}
    </div>
    <div class="footer">Generated by ⚡ Nexoro AI — Professional Catalogue Builder</div>
    </body></html>`)
    w.document.close()
    w.print()
  }

  return (
    <main className="min-h-screen bg-gray-950 text-white p-4 md:p-8">
      <div className="max-w-5xl mx-auto space-y-6">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <h1 className="text-3xl font-bold">🛍️ Catalogue Generator</h1>
            <p className="text-gray-500 mt-1">Catalogue produits professionnel généré par IA</p>
          </div>
          {data && <button onClick={exportPDF} className="bg-green-600 hover:bg-green-500 text-white font-semibold py-2 px-6 rounded-xl">📥 Export PDF</button>}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 space-y-4">
            <input value={business} onChange={e => setBusiness(e.target.value)}
              placeholder="Business name — Ex: Luxury Watches Store"
              className="w-full bg-gray-800 border border-gray-700 rounded-xl p-3 text-white placeholder-gray-500 focus:outline-none focus:border-indigo-500" />
            <textarea value={products} onChange={e => setProducts(e.target.value)}
              placeholder="Products/Services — Ex: Rolex watches, Omega, Cartier, luxury accessories, jewelry..."
              className="w-full bg-gray-800 border border-gray-700 rounded-xl p-3 text-white placeholder-gray-500 resize-none h-28 focus:outline-none focus:border-indigo-500" />
          </div>
          <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 space-y-4">
            <div>
              <h2 className="text-sm font-medium text-gray-400 mb-3">Style</h2>
              <div className="space-y-2">
                {styles.map(s => (
                  <button key={s} onClick={() => setStyle(s)}
                    className={`w-full text-left p-2 rounded-xl text-sm transition-all ${style === s ? 'bg-indigo-600 text-white' : 'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}>
                    {s}
                  </button>
                ))}
              </div>
            </div>
            <div>
              <h2 className="text-sm font-medium text-gray-400 mb-2">Language</h2>
              <div className="flex gap-2 flex-wrap">
                {languages.map(l => (
                  <button key={l} onClick={() => setLanguage(l)}
                    className={`px-3 py-1.5 rounded-xl text-xs transition-all ${language === l ? 'bg-indigo-600 text-white' : 'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}>
                    {l}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>

        <button onClick={generate} disabled={loading || !business || !products}
          className="w-full bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 disabled:opacity-50 text-white font-bold py-4 rounded-xl transition-all text-lg">
          {loading ? '🛍️ Generating catalogue...' : '🛍️ Generate Professional Catalogue'}
        </button>

        {data && (
          <div className="space-y-6">
            <div className="bg-gradient-to-r from-indigo-600 to-purple-600 rounded-2xl p-6 text-center">
              <h2 className="text-2xl font-bold">{data.business_name}</h2>
              <p className="text-white/80 mt-1">{data.tagline}</p>
              <p className="text-white/60 text-sm mt-2">{data.description}</p>
            </div>

            {data.categories?.map((cat: any) => (
              <div key={cat.name} className="bg-gray-900 border border-gray-800 rounded-2xl p-6">
                <h3 className="text-lg font-bold mb-4">{cat.emoji} {cat.name}</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {cat.products?.map((p: any) => (
                    <div key={p.name} className="bg-gray-800 rounded-xl p-4 relative">
                      {p.badge && (
                        <span className="absolute top-3 right-3 bg-indigo-600 text-white text-xs px-2 py-1 rounded-full font-bold">
                          {p.badge}
                        </span>
                      )}
                      <div className="text-3xl mb-2">{p.emoji}</div>
                      <h4 className="font-bold text-white mb-1">{p.name}</h4>
                      <p className="text-gray-400 text-xs mb-3 leading-relaxed">{p.description}</p>
                      <p className="text-indigo-400 font-bold text-lg mb-2">{p.price}</p>
                      <ul className="space-y-1">
                        {p.features?.map((f: string) => (
                          <li key={f} className="text-xs text-gray-400 flex gap-1">
                            <span className="text-green-400">✓</span>{f}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </main>
  )
}
